# 使用advs来生成Summary Table

In [1]:
import pandas as pd
import numpy as np
from plotnine import *
%matplotlib inline


advs = pd.read_sas("./data/processed/advs.xpt")

In [2]:
from pathlib import Path
from datetime import datetime

In [3]:
advs1 = advs.loc[(advs["ANL01FL"] == b"Y") & (advs["PARAM"] == b'Diastolic Blood Pressure (mmHg)')]
gg = advs1.groupby(["TRTPN","TRTP","AVISITN","AVISIT"])

In [4]:
advs1.head()

,STUDYID,SITEID,USUBJID,AGE,AGEGR1,AGEGR1N,RACE,RACEN,SEX,SAFFL,...,AVAL,BASE,BASETYPE,CHG,PCHG,VISITNUM,VISIT,VSSEQ,ANL01FL,ABLFL
2,b'CDISCPILOT01',b'701',b'01-701-1015',63.0,b'<65',1.0,b'WHITE',1.0,b'F',b'Y',...,56.0,56.0,b'AFTER LYING DOWN FOR 5 MINUTES',5.397605e-79,5.397605e-79,3.0,b'BASELINE',7.0,b'Y',b'Y'
4,b'CDISCPILOT01',b'701',b'01-701-1015',63.0,b'<65',1.0,b'WHITE',1.0,b'F',b'Y',...,56.0,56.0,b'AFTER LYING DOWN FOR 5 MINUTES',5.397605e-79,5.397605e-79,4.0,b'WEEK 2',13.0,b'Y',b''
5,b'CDISCPILOT01',b'701',b'01-701-1015',63.0,b'<65',1.0,b'WHITE',1.0,b'F',b'Y',...,64.0,56.0,b'AFTER LYING DOWN FOR 5 MINUTES',8.000000e+00,1.428571e+01,5.0,b'WEEK 4',16.0,b'Y',b''
7,b'CDISCPILOT01',b'701',b'01-701-1015',63.0,b'<65',1.0,b'WHITE',1.0,b'F',b'Y',...,55.0,56.0,b'AFTER LYING DOWN FOR 5 MINUTES',-1.000000e+00,-1.785714e+00,7.0,b'WEEK 6',22.0,b'Y',b''
8,b'CDISCPILOT01',b'701',b'01-701-1015',63.0,b'<65',1.0,b'WHITE',1.0,b'F',b'Y',...,67.0,56.0,b'AFTER LYING DOWN FOR 5 MINUTES',1.100000e+01,1.964286e+01,8.0,b'WEEK 8',25.0,b'Y',b''

In [5]:
gg["PARAM"].value_counts()

TRTPN         TRTP                     AVISITN       AVISIT               PARAM
5.397605e-79  b'Placebo'               5.397605e-79  b'Baseline'          b'Diastolic Blood Pressure (mmHg)'    255
                                       2.000000e+00  b'Week 2'            b'Diastolic Blood Pressure (mmHg)'    252
                                       4.000000e+00  b'Week 4'            b'Diastolic Blood Pressure (mmHg)'    246
                                       6.000000e+00  b'Week 6'            b'Diastolic Blood Pressure (mmHg)'    228
                                       8.000000e+00  b'Week 8'            b'Diastolic Blood Pressure (mmHg)'    219
                                       1.200000e+01  b'Week 12'           b'Diastolic Blood Pressure (mmHg)'    207
                                       1.600000e+01  b'Week 16'           b'Diastolic Blood Pressure (mmHg)'    204
                                       2.000000e+01  b'Week 20'           b'Diastolic Blood Pressure (mmHg)'    198
                                       2.400000e+01  b'Week 24'           b'Diastolic Blood Pressure (mmHg)'    177
                                       2.600000e+01  b'Week 26'           b'Diastolic Blood Pressure (mmHg)'    174
                                       9.900000e+01  b'End of Treatment'  b'Diastolic Blood Pressure (mmHg)'    246
5.400000e+01  b'Xanomeline Low Dose'   5.397605e-79  b'Baseline'          b'Diastolic Blood Pressure (mmHg)'    252
                                       2.000000e+00  b'Week 2'            b'Diastolic Blood Pressure (mmHg)'    252
                                       4.000000e+00  b'Week 4'            b'Diastolic Blood Pressure (mmHg)'    216
                                       6.000000e+00  b'Week 6'            b'Diastolic Blood Pressure (mmHg)'    195
                                       8.000000e+00  b'Week 8'            b'Diastolic Blood Pressure (mmHg)'    180
                                       1.200000e+01  b'Week 12'           b'Diastolic Blood Pressure (mmHg)'    156
                                       1.600000e+01  b'Week 16'           b'Diastolic Blood Pressure (mmHg)'    126
                                       2.000000e+01  b'Week 20'           b'Diastolic Blood Pressure (mmHg)'     90
                                       2.400000e+01  b'Week 24'           b'Diastolic Blood Pressure (mmHg)'     81
                                       2.600000e+01  b'Week 26'           b'Diastolic Blood Pressure (mmHg)'     75
                                       9.900000e+01  b'End of Treatment'  b'Diastolic Blood Pressure (mmHg)'    216
8.100000e+01  b'Xanomeline High Dose'  5.397605e-79  b'Baseline'          b'Diastolic Blood Pressure (mmHg)'    252
                                       2.000000e+00  b'Week 2'            b'Diastolic Blood Pressure (mmHg)'    243
                                       4.000000e+00  b'Week 4'            b'Diastolic Blood Pressure (mmHg)'    219
                                       6.000000e+00  b'Week 6'            b'Diastolic Blood Pressure (mmHg)'    203
                                       8.000000e+00  b'Week 8'            b'Diastolic Blood Pressure (mmHg)'    168
                                       1.200000e+01  b'Week 12'           b'Diastolic Blood Pressure (mmHg)'    150
                                       1.600000e+01  b'Week 16'           b'Diastolic Blood Pressure (mmHg)'    111
                                       2.000000e+01  b'Week 20'           b'Diastolic Blood Pressure (mmHg)'     96
                                       2.400000e+01  b'Week 24'           b'Diastolic Blood Pressure (mmHg)'     90
                                       2.600000e+01  b'Week 26'           b'Diastolic Blood Pressure (mmHg)'     84
                                       9.900000e+01  b'End of Treatment'  b'Diastolic Blood Pressure (mmHg)'    219
Name: PARAM, dtype: int64

In [98]:
sum = gg["AVAL"].agg({"count","mean","std","sem","median","min","max"})

In [99]:
list(sum)

['median', 'sem', 'count', 'mean', 'max', 'std', 'min']

In [100]:
sum["mean"] = sum["mean"].round(1).apply(str)
sum["std"] = sum["std"].round(2).apply(str)
sum["sem"] = sum["sem"].round(2).apply(str)
sum["median"] = sum["median"].round(1).apply(str)
sum["min"] = sum["min"].round(0).apply(str)
sum["max"] = sum["max"].round(0).apply(str)
sum.head()

                                                 median   sem  count  mean  \
TRTPN        TRTP       AVISITN      AVISIT
5.397605e-79 b'Placebo' 5.397605e-79 b'Baseline'   78.0  0.68    255  77.1
                        2.000000e+00 b'Week 2'     74.0  0.66    252  74.5
                        4.000000e+00 b'Week 4'     76.0  0.73    246  75.4
                        6.000000e+00 b'Week 6'     74.0  0.68    228  74.5
                        8.000000e+00 b'Week 8'     76.0  0.63    219  75.2

                                                    max    std   min
TRTPN        TRTP       AVISITN      AVISIT
5.397605e-79 b'Placebo' 5.397605e-79 b'Baseline'  110.0  10.91  40.0
                        2.000000e+00 b'Week 2'    100.0  10.42  45.0
                        4.000000e+00 b'Week 4'    100.0  11.46  39.0
                        6.000000e+00 b'Week 6'    110.0   10.2  48.0
                        8.000000e+00 b'Week 8'    101.0   9.29  49.0

In [101]:
sum.dtypes

median    object
sem       object
count      int64
mean      object
max       object
std       object
min       object
dtype: object

In [102]:
sum.reset_index(inplace=True)
sum.sort_values(by=["AVISITN","AVISIT","TRTPN","TRTP"])

,TRTPN,TRTP,AVISITN,AVISIT,median,sem,count,mean,max,std,min
0,5.397605e-79,b'Placebo',5.397605e-79,b'Baseline',78.0,0.68,255,77.1,110.0,10.91,40.0
11,5.400000e+01,b'Xanomeline Low Dose',5.397605e-79,b'Baseline',76.0,0.65,252,76.4,108.0,10.25,48.0
22,8.100000e+01,b'Xanomeline High Dose',5.397605e-79,b'Baseline',79.5,0.65,252,78.3,108.0,10.27,51.0
1,5.397605e-79,b'Placebo',2.000000e+00,b'Week 2',74.0,0.66,252,74.5,100.0,10.42,45.0
12,5.400000e+01,b'Xanomeline Low Dose',2.000000e+00,b'Week 2',76.0,0.62,251,76.2,102.0,9.89,45.0
23,8.100000e+01,b'Xanomeline High Dose',2.000000e+00,b'Week 2',77.0,0.69,243,76.4,118.0,10.78,43.0
2,5.397605e-79,b'Placebo',4.000000e+00,b'Week 4',76.0,0.73,246,75.4,100.0,11.46,39.0
13,5.400000e+01,b'Xanomeline Low Dose',4.000000e+00,b'Week 4',78.0,0.64,216,76.0,102.0,9.35,50.0
24,8.100000e+01,b'Xanomeline High Dose',4.000000e+00,b'Week 4',78.0,0.65,219,76.8,100.0,9.58,54.0
3,5.397605e-79,b'Placebo',6.000000e+00,b'Week 6',74.0,0.68,228,74.5,110.0,10.2,48.0
14,5.400000e+01,b'Xanomeline Low Dose',6.000000e+00,b'Week 6',76.0,0.66,195,74.9,100.0,9.18,50.0
25,8.100000e+01,b'Xanomeline High Dose',6.000000e+00,b'Week 6',76.0,0.69,203,75.3,98.0,9.9,52.0
4,5.397605e-79,b'Placebo',8.000000e+00,b'Week 8',76.0,0.63,219,75.2,101.0,9.29,49.0
15,5.400000e+01,b'Xanomeline Low Dose',8.000000e+00,b'Week 8',74.5,0.8,180,75.4,100.0,10.75,52.0
26,8.100000e+01,b'Xanomeline High Dose',8.000000e+00,b'Week 8',78.0,0.72,168,77.4,98.0,9.28,54.0
5,5.397605e-79,b'Placebo',1.200000e+01,b'Week 12',73.0,0.76,207,74.3,104.0,10.92,49.0
16,5.400000e+01,b'Xanomeline Low Dose',1.200000e+01,b'Week 12',75.0,0.87,156,75.7,100.0,10.84,50.0
27,8.100000e+01,b'Xanomeline High Dose',1.200000e+01,b'Week 12',76.0,0.75,150,74.6,92.0,9.21,54.0
6,5.397605e-79,b'Placebo',1.600000e+01,b'Week 16',76.5,0.78,204,75.1,98.0,11.1,49.0
17,5.400000e+01,b'Xanomeline Low Dose',1.600000e+01,b'Week 16',75.5,0.9,126,75.2,98.0,10.13,55.0
28,8.100000e+01,b'Xanomeline High Dose',1.600000e+01,b'Week 16',78.0,0.87,111,76.0,92.0,9.12,50.0
7,5.397605e-79,b'Placebo',2.000000e+01,b'Week 20',72.0,0.75,198,73.4,100.0,10.58,48.0
18,5.400000e+01,b'Xanomeline Low Dose',2.000000e+01,b'Week 20',72.0,1.03,90,73.7,98.0,9.74,51.0
29,8.100000e+01,b'Xanomeline High Dose',2.000000e+01,b'Week 20',72.0,1.06,96,74.1,98.0,10.36,54.0
8,5.397605e-79,b'Placebo',2.400000e+01,b'Week 24',74.0,0.89,177,73.8,117.0,11.83,44.0
19,5.400000e+01,b'Xanomeline Low Dose',2.400000e+01,b'Week 24',76.0,1.08,81,76.2,98.0,9.76,57.0
30,8.100000e+01,b'Xanomeline High Dose',2.400000e+01,b'Week 24',75.5,1.08,90,74.9,98.0,10.24,50.0
9,5.397605e-79,b'Placebo',2.600000e+01,b'Week 26',72.0,0.83,174,72.6,98.0,10.95,39.0
20,5.400000e+01,b'Xanomeline Low Dose',2.600000e+01,b'Week 26',72.0,1.14,75,72.9,92.0,9.89,56.0
31,8.100000e+01,b'Xanomeline High Dose',2.600000e+01,b'Week 26',74.0,1.15,84,74.5,93.0,10.52,50.0
10,5.397605e-79,b'Placebo',9.900000e+01,b'End of Treatment',74.0,0.7,246,74.1,100.0,11.04,39.0
21,5.400000e+01,b'Xanomeline Low Dose',9.900000e+01,b'End of Treatment',72.0,0.62,216,73.8,102.0,9.13,51.0
32,8.100000e+01,b'Xanomeline High Dose',9.900000e+01,b'End of Treatment',76.0,0.7,219,75.1,99.0,10.38,50.0

In [133]:
sum_t=pd.melt(sum,id_vars=["AVISITN","AVISIT","TRTPN","TRTP"],var_name='stats', value_name='valn')

In [134]:
sum_t.head()

        AVISITN       AVISIT         TRTPN        TRTP   stats  valn
0  5.397605e-79  b'Baseline'  5.397605e-79  b'Placebo'  median  78.0
1  2.000000e+00    b'Week 2'  5.397605e-79  b'Placebo'  median  74.0
2  4.000000e+00    b'Week 4'  5.397605e-79  b'Placebo'  median  76.0
3  6.000000e+00    b'Week 6'  5.397605e-79  b'Placebo'  median  74.0
4  8.000000e+00    b'Week 8'  5.397605e-79  b'Placebo'  median  76.0

In [135]:
sum_t.dtypes

AVISITN    float64
AVISIT      object
TRTPN      float64
TRTP        object
stats       object
valn        object
dtype: object

In [136]:
# refer to http://pbpython.com/pandas_dtypes.html
sum_t["AVISITN"] = sum_t["AVISITN"].astype("int")
sum_t["TRTPN"] = sum_t["TRTPN"].astype("int")

In [137]:
sum_t.dtypes

AVISITN     int64
AVISIT     object
TRTPN       int64
TRTP       object
stats      object
valn       object
dtype: object

In [138]:
sum_t.head()

   AVISITN       AVISIT  TRTPN        TRTP   stats  valn
0        0  b'Baseline'      0  b'Placebo'  median  78.0
1        2    b'Week 2'      0  b'Placebo'  median  74.0
2        4    b'Week 4'      0  b'Placebo'  median  76.0
3        6    b'Week 6'      0  b'Placebo'  median  74.0
4        8    b'Week 8'      0  b'Placebo'  median  76.0

In [139]:
sum_t.loc[sum_t["stats"] == "count", "statn"] = 1
sum_t.loc[sum_t["stats"] == "mean", "statn"] = 2
sum_t.loc[sum_t["stats"] == "median", "statn"] = 3
sum_t.loc[sum_t["stats"] == "std", "statn"] = 4
sum_t.loc[sum_t["stats"] == "sem", "statn"] = 5
sum_t.loc[sum_t["stats"] == "min", "statn"] = 6
sum_t.loc[sum_t["stats"] == "max", "statn"] = 7

In [140]:
sum_t.loc[sum_t["stats"] == "count", "statlabel"] = "n"
sum_t.loc[sum_t["stats"] == "mean", "statlabel"] = "Mean"
sum_t.loc[sum_t["stats"] == "median", "statlabel"] = "Median"
sum_t.loc[sum_t["stats"] == "std", "statlabel"] = "S.D."
sum_t.loc[sum_t["stats"] == "sem", "statlabel"] = "S.E."
sum_t.loc[sum_t["stats"] == "min", "statlabel"] = "Min"
sum_t.loc[sum_t["stats"] == "max", "statlabel"] = "Max"

In [141]:
sum_t.head()

   AVISITN       AVISIT  TRTPN        TRTP   stats  valn  statn statlabel
0        0  b'Baseline'      0  b'Placebo'  median  78.0    3.0    Median
1        2    b'Week 2'      0  b'Placebo'  median  74.0    3.0    Median
2        4    b'Week 4'      0  b'Placebo'  median  76.0    3.0    Median
3        6    b'Week 6'      0  b'Placebo'  median  74.0    3.0    Median
4        8    b'Week 8'      0  b'Placebo'  median  76.0    3.0    Median

In [142]:
sum_t["varn"] = 1
sum_t["var"] = "AVAL"
sum_t["varlabel"] = b'Diastolic Blood Pressure (mmHg)'
sum_t.head()

,AVISITN,AVISIT,TRTPN,TRTP,stats,valn,statn,statlabel,varn,var,varlabel
0,0,b'Baseline',0,b'Placebo',median,78.0,3.0,Median,1,AVAL,b'Diastolic Blood Pressure (mmHg)'
1,2,b'Week 2',0,b'Placebo',median,74.0,3.0,Median,1,AVAL,b'Diastolic Blood Pressure (mmHg)'
2,4,b'Week 4',0,b'Placebo',median,76.0,3.0,Median,1,AVAL,b'Diastolic Blood Pressure (mmHg)'
3,6,b'Week 6',0,b'Placebo',median,74.0,3.0,Median,1,AVAL,b'Diastolic Blood Pressure (mmHg)'
4,8,b'Week 8',0,b'Placebo',median,76.0,3.0,Median,1,AVAL,b'Diastolic Blood Pressure (mmHg)'

In [143]:
#final=sum_t.pivot_table(index=["AVISITN","AVISIT","varn","var","varlabel","statn","stats","statlabel"], columns=["TRTPN","TRTP"], values='valn').reset_index()
#final=sum_t.pivot(index=["AVISITN","AVISIT","varn","var","varlabel","statn","stats","statlabel"], columns=["TRTP"]).reset_index()
#final.head()

sum_t = sum_t.drop(columns=["TRTPN"])
sum_t = sum_t.set_index(["AVISITN","AVISIT","varn","var","varlabel","statn","stats","statlabel","TRTP"])

In [145]:
list(sum_t)

['valn']

In [146]:
final = sum_t.unstack().reset_index()
final.head()

     AVISITN       AVISIT varn   var                            varlabel  \
TRTP
0          0  b'Baseline'    1  AVAL  b'Diastolic Blood Pressure (mmHg)'
1          0  b'Baseline'    1  AVAL  b'Diastolic Blood Pressure (mmHg)'
2          0  b'Baseline'    1  AVAL  b'Diastolic Blood Pressure (mmHg)'
3          0  b'Baseline'    1  AVAL  b'Diastolic Blood Pressure (mmHg)'
4          0  b'Baseline'    1  AVAL  b'Diastolic Blood Pressure (mmHg)'

     statn   stats statlabel       valn                          \
TRTP                         b'Placebo' b'Xanomeline High Dose'
0      1.0   count         n        255                     252
1      2.0    mean      Mean       77.1                    78.3
2      3.0  median    Median       78.0                    79.5
3      4.0     std      S.D.      10.91                   10.27
4      5.0     sem      S.E.       0.68                    0.65


TRTP b'Xanomeline Low Dose'
0                       252
1                      76.4
2                      76.0
3                     10.25
4                      0.65

In [147]:
list(final)

[('AVISITN', ''),
 ('AVISIT', ''),
 ('varn', ''),
 ('var', ''),
 ('varlabel', ''),
 ('statn', ''),
 ('stats', ''),
 ('statlabel', ''),
 ('valn', b'Placebo'),
 ('valn', b'Xanomeline High Dose'),
 ('valn', b'Xanomeline Low Dose')]

In [148]:
# export to html
final.to_html("./reports/01_advs_diabp_aval_sum.html")

In [153]:
#!conda install -y xlsxwriter

In [154]:
#import xlsxwriter
#writer_orig = pd.ExcelWriter('./reports/simple.xlsx', engine='xlsxwriter')
#final.to_excel(writer_orig, index=False, sheet_name='diabp_aval_sum')
#writer_orig.save()